fix issue #14, issue #20
drgn-hart/Countdown-Timer pull request #21
Opened 2020-10-07 20:42 UTC by yuanLeeMidori

Hi, I've added the pause and resume feature to the extension. Please let me know if there is anything you want me to modify, including coding style and UI. 

Also, I add one setting of the font color during the rand of 5-10 minutes. I set it to black to improve accessibility.

2020-10-09 13:15 UTC, drgn-hart commented
Thanks for working on this. I will need some time to review and merge as I am preoccupied with some other work. Will try to get back to you by next week

2020-10-10 01:43 UTC, yuanLeeMidori commented
No worries! Take your time. Let me know if there is anything I can do

2020-10-12 14:00 UTC, drgn-hart requested changes
Overall looks good. Can you run _eslint src/**_ and fix the linter errors in the code?

2020-10-12 14:00 UTC, drgn-hart commented on src/core/timer.js
> +  debugger;
Remove debugger statement

2020-10-12 15:32 UTC, yuanLeeMidori commented on src/core/timer.js
> +  debugger;
Thank you for checking my code. Sorry about leaving the debugger. I've removed it and pushed the change.

2020-10-18 03:53 UTC, drgn-hart approved these changes

2020-10-18 03:54 UTC, merged